# When the nightstand stand button is pressed and sensor is on turn on the nightstand light - emulating a toggle switch

- alias: 'Melodie nightstand ON dash '
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.melodiedash
    from: '0'
    to: '1'
  action:
    - service: switch.turn_on
      entity_id: switch.melodie_nightstand_
      
##When the nightstand stand button is pressed and sensor is off turn off the nightstand light - emulating a toggle switch

- alias: 'Melodie nightstand OFF dash '
  initial_state: True
  trigger:
    platform: state
    entity_id: sensor.melodiedash
    from: '1'
    to: '0'
  action:
    - service: switch.turn_off
      entity_id: switch.melodie_nightstand_

#### Begin -Change the sensor used by the dash button so it always has current state of light

- alias: 'zzz Nightstand sensor to ON'
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.melodie_nightstand_
    from: 'off'
    to: 'on'
  action:
    - service: shell_command.melodie_nightstand_on

- alias: 'zzz Nightstand sensor to OFF'
  initial_state: True
  trigger:
    platform: state
    entity_id: switch.melodie_nightstand_
    from: 'on'
    to: 'off'
  action:
    - service: shell_command.melodie_nightstand_off


#### End - Change the sensor used by the dash button so it always has current state of light



      
