#        name: Raise Shade any wind  GE set threshold mph

- alias: 'Raise Shade any wind  GE set threshold mph'
  trigger:
    - platform: template
      value_template: '{{ states.sensor.pws_wind_mph.state | int >= states.sensor.wind_speed_threshold.state | int }}'
    - platform: template
      value_template: '{{ states.sensor.pws_wind_gust_mph.state | int >= states.sensor.wind_speed_threshold.state | int }}'
  condition:
    condition: state
    entity_id: switch.somfy
    # entity_id: switch.router_fan
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id:
      - switch.somfy
      # entity_id:
      # - switch.router_fan
    - service: persistent_notification.create
      data:
        message: ' {{states.sensor.date__time.state}} Sun Shade Raised WS={{ states.sensor.pws_wind_mph.state}} GUST={{ states.sensor.pws_wind_gust_mph.state}} TH={{ states.sensor.wind_speed_threshold.state}}'
        title: "Sun Shade Raised"
        