                                                                
# Turn off Patio Light sunset group at (sunset + 1hr )
- alias: 'Patio CF Light Sunrise off'
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
    # Optional time offset. +/-HH:MM:SS
    offset: '+00:10:00'
  action:
    - service: switch.turn_off
      entity_id: switch.patiolight

# check if furnace filter change time
- alias: 'zzz check furnace filter change date'
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
    # Optional time offset. +/-HH:MM:SS
    # offset: '+00:03:00'
  condition:
    condition: template
    value_template: '{{ states.sensor.date.state >= states.sensor.furnacefilter.state }}'
  action:
    service: persistent_notification.create
    data:
      message: "Furnace Filter"
      title: "Time to change furnace filter"
      


- alias: 'shade down at Dawn'
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
    # Optional time offset. +/-HH:MM:SS
    offset: '-00:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.somfy
      




- alias: 'Vacation Return day adjust Nest temp'
  trigger:
    platform: sun
    event: sunrise
  condition:
    condition: template
    value_template: '{{ states.sensor.date.state == states.input_datetime.vacation_return_date.state }}'
  action:
    - service: persistent_notification.create
      data:
        message: "Vacation Return"
        title: "Returning today"
    - service: climate.set_temperature
      data_template:
        entity_id: climate.arizona_arizona
        temperature: 72
        
- alias: 'Morning HVAC temp drop'
  trigger:
    platform: sun
    event: sunrise
  # condition:
  #   condition: template
  #   value_template: '{{ states.sensor.date.state >= states.input_datetime.vacation_return_date.state }}'  # look for night mode
  action:
    # - service: persistent_notification.create
    #   data:
    #     message: "Vacation Return"
    #     title: "Returning today"
    - service: climate.set_temperature
      data_template:
        entity_id: climate.arizona_arizona
        temperature: '{{ states.climate.arizona_arizona.attributes.temperature - 1 }}'
        #temperature: 72