

- alias: 'zz Auto Renew SSL Cert'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 29
  action:
    service: shell_command.renew_ssl
    
# fire when weather alert changes to 1 show the group in the weather view

- alias: 'zz Weather alert 1'
  trigger:
    platform: state
    entity_id: sensor.pws_alerts
    from: '0'
    to: '1'
  action:
    service: group.set_visibility
    entity_id: group.weather_alert_group
    data:
      visible: True

# # fire when weather alert changes to 0 hide the group in the weather view

- alias: 'zz Weather alert 0'
  trigger:
    platform: state
    entity_id: sensor.pws_alerts
    from: '1'
    to: '0'
  action:
    service: group.set_visibility
    entity_id: group.weather_alert_group
    data:
      visible: False
# fire when HA restarts and Hide aert group if no active alert

- alias: 'zz Weatheralert hide on HA start if no active alert'
  hide_entity: False
  trigger:
      platform: homeassistant
      event: start
  condition:
    condition: state
    entity_id: sensor.pws_alerts
    state: '0'
  action:
    service: group.set_visibility
    entity_id: group.weather_alert_group
    data:
      visible: False

- alias: 'zzz toggle automations off'
  trigger:
    platform: state
    entity_id: input_boolean.on_vaca
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.automations_to_toggle_g

- alias: 'zzz toggle automations on'
  trigger:
    platform: state
    entity_id: input_boolean.on_vaca
    from: 'on'
    to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: group.automations_to_toggle_



- alias: 'LR Sensor Off Timer'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.test1_motion
    to: 'on'
    # for:
    # seconds: 4
  action:
    - delay: 00:00:10
    - service: mqtt.publish
      data:
        topic: 'home/433toMQTT'
        payload: '1051530off'
     # retain: 'true'
      
- alias: 'BR Upper Sensor Off Timer'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.test2_motion
    to: 'on'
    # for:
    # seconds: 4
  action:
    - delay: 00:00:10
    - service: mqtt.publish
      data:
        topic: 'home/433toMQTT'
        payload: '4551562off'
     # retain: 'true'
      

- alias: 'Melodie BR Sensor Off Timer'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.br_melodie
    to: 'on'
    # for:
    # seconds: 4
  action:
    - delay: 00:00:10
    - service: mqtt.publish
      data:
        topic: 'home/433toMQTT'
        payload: '3747914off'
      #retain: 'true'
 
 
- alias: 'Kitchen Sensor Off Timer'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    to: 'on'
    # for:
    # seconds: 6
  action:
    - delay: 00:00:10
    - service: mqtt.publish
      data:
        topic: 'home/433toMQTT'
        payload: '2330698off'
      #retain: 'true'
 
 
- alias: 'Entry Sensor Off Timer'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.entry_motion
    to: 'on'
    # for:
    # seconds: 4
  action:
    - delay: 00:00:10
    - service: mqtt.publish
      data:
        topic: 'home/433toMQTT'
        payload: '831562off'
      #retain: 'true'
      

- alias: 'Kitchen Cabinet Off Timer'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_cabinet
    to: 'on'
    # for:
    # seconds: 4
  action:
    - delay: 00:00:10
    - service: mqtt.publish
      data:
        topic: 'home/433toMQTT'
        payload: '6881354off'
      #retain: 'true'

      
- alias: 'xx ios msg counts'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: notify
      service: ios_michaels_iphone
  action:
    # putting the delay ensure that the event makes it to the log in the event this is the first notify
    - delay: 00:00:05
    - service: shell_command.iosnotifycount

#call_service|{"domain": "notify", "service": "ios_michaels_iphone", "service_data": {"message": "Here i

- alias: 'zzz LR sensor power reset'
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_gw
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: switch.patio_outlet
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.patio_outlet
    - service: homeassistant.turn_on
      entity_id: switch.patio_outlet
      
 
 
 
 # #-autodoc
# #-autodoc        name:
# #-autodoc description:
# #-autodoc        file:
# #-autodoc
# - alias: Something opened
#   trigger:
#     platform: state
#     entity_id: !secret openings_to_watch
#     from: 'off'
#     to: 'on'
#   action:
#     service: persistent_notification.create
#     data_template:
#       message: ' {{states.sensor.date__time.state}} - {{ trigger.from_state.attributes.friendly_name}} has been opened'
#       title: "Something Opened"
# - alias: Something closed
#   trigger:
#     platform: state
#     entity_id: !secret openings_to_watch
#     from: 'on'
#     to: 'off'
#   action:
#     service: persistent_notification.create
#     data_template:
#       message:  ' {{states.sensor.date__time.state}} - {{ trigger.from_state.attributes.friendly_name}} has been closed'
#       title: "Something Closed"