# Turn on stuff in sunset group at (sunset - 30min )
#-autodoc
#-autodoc        name: LR switch Sunset(-30) on
#-autodoc description: Turn on the living room light plugged into the switched outlet and wemo outlet 30 minutes before sunset.
#-autodoc        file: sunset.yaml
#-autodoc
- alias: 'LR switch Sunset(-30) on'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:20:00'
  action:
    - service: switch.turn_on
      entity_id:
      - switch.lr_switch
      - switch.lr_light


#-autodoc
#-autodoc        name: Patio CF Light Sunset  on
#-autodoc description: Turn on the patio ceiling fan light sunset.
#-autodoc        file: sunset.yaml
#-autodoc
# - alias: 'Patio CF Light Sunset on'
#   trigger:
#     platform: sun
#     event: sunset
#   action:
#     - service: switch.turn_on
#       entity_id:
#       - switch.patio_outlet
#       - switch.lr_light


- alias: 'Patio CF Light on'
  initial_state: True
  trigger:
    platform: time
    at: '23:00:00'
  action:
   - service: switch.turn_on
     entity_id:
     - switch.patiolight